events { worker_connections 1024; }

http {
    # Включаем поддержку правильных типов файлов (CSS, JS и т.д.)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Перенаправляем все запросы на наш контейнер с FastAPI
        location / {
            proxy_pass http://api:8000;
            
            # Передаем реальные IP-адреса клиентов, чтобы работал наш Rate Limiter!
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}